version: '3.3'

networks:
  ktor-exposed-with-mysql:
    driver: bridge

services:
  db:
    container_name: mysql8
    image: mysql:8
    restart: always
    ports:
      - "8306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: p@ss
      MYSQL_DATABASE: tutorial_db
      MYSQL_USER: german
      MYSQL_PASSWORD: p@ss
    networks:
      - ktor-exposed-with-mysql